name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 20.x
          - 22.x
        # - 24.x # Disabled for now because it's failing on jest mocked modules
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Clean cache
        run: npm cache clean --force

      - name: Verify Node.js version
        run: node -v

      - name: Verify Npm version
        run: npm -v

      - name: Install matterbridge globally
        run: npm install -g matterbridge@latest

      - name: Install plugin dependencies
        run: npm ci

      - name: Link matterbridge in the project
        run: npm link matterbridge

      - name: Lint the plugin
        run: npm run lint

      - name: Test the plugin
        run: npm run test

      - name: Build the plugin
        run: npm run build
