name: Publish to npm

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Clean cache
        run: npm cache clean --force

      - name: Verify Node.js version
        run: node -v

      - name: Verify Npm version
        run: npm -v

      - name: Install matterbridge globally
        run: npm install -g matterbridge@latest

      - name: Install plugin dependencies
        run: npm ci

      - name: Link matterbridge in the project
        run: npm link matterbridge

      - name: Lint the plugin
        run: npm run lint

      - name: Test the plugin
        run: npm run test

      - name: Build the plugin
        run: npm run build

      - name: Publish the plugin to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
